import json
import os
import shutil
import tempfile
import time
import zipfile
import subprocess
from pathlib import Path
from typing import List, Dict, Any, Optional


def extract_title_from_md(md_path: Path) -> str:
    """Extract first H1 heading from markdown file, fallback to filename stem."""
    try:
        with open(md_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("# "):
                    return line[2:].strip()
    except Exception:
        pass
    return md_path.stem


def create_publish_bundle(
    article_paths: List[Path],
    cover_mapping: Dict[str, Dict[str, Path]],  # { article_stem: { platform: cover_path } }
    platforms: List[str],
    mode: str,
    output_zip_path: Path,
    job_id: Optional[str] = None,
    theme_mapping: Optional[Dict[str, Dict[str, str]]] = None,
) -> Path:
    """
    Creates a zip bundle containing markdown articles, cover images, and a manifest.json.
    
    Args:
        article_paths: List of local paths to markdown files.
        cover_mapping: Mapping of article stem to dictionary of platform cover images.
        platforms: Target platforms to publish.
        mode: "publish" or "draft"
        output_zip_path: Target path to write the zip file.
        job_id: Optional specific job ID (autogenerated if missing).
    """
    job_id = job_id or f"job_{int(time.time())}"
    output_zip_path = Path(output_zip_path)
    output_zip_path.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as temp_dir_str:
        temp_dir = Path(temp_dir_str)
        articles_dir = temp_dir / "articles"
        covers_dir = temp_dir / "covers"
        
        articles_dir.mkdir()
        covers_dir.mkdir()

        manifest_articles = []

        for index, art_path in enumerate(article_paths):
            art_path = Path(art_path)
            if not art_path.exists():
                raise FileNotFoundError(f"Article not found: {art_path}")

            # Copy article
            dest_art_name = f"art_{index:03d}_{art_path.name}"
            dest_art_path = articles_dir / dest_art_name
            shutil.copy2(art_path, dest_art_path)

            article_title = extract_title_from_md(art_path)
            article_covers = {}

            # Copy associated covers
            stem = art_path.stem
            if stem in cover_mapping:
                for platform, cover_path in cover_mapping[stem].items():
                    cover_path = Path(cover_path)
                    if cover_path.exists():
                        dest_cover_name = f"cover_{index:03d}_{platform}_{cover_path.name}"
                        dest_cover_path = covers_dir / dest_cover_name
                        shutil.copy2(cover_path, dest_cover_path)
                        article_covers[platform] = f"covers/{dest_cover_name}"

            article_themes = dict((theme_mapping or {}).get(art_path.stem, {}))

            manifest_articles.append({
                "article_id": f"art_{index:03d}",
                "title": article_title,
                "markdown_path": f"articles/{dest_art_name}",
                "covers": article_covers,
                "themes": article_themes,
                "original_filename": art_path.name
            })

        manifest = {
            "job_id": job_id,
            "mode": mode,
            "platforms": platforms,
            "articles": manifest_articles,
            "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "policy": {
                "cover_required_where_supported": True,
                "on_platform_limit": "defer",
                "on_cover_failure": "save_draft"
            }
        }

        # Write manifest
        with open(temp_dir / "manifest.json", "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2, ensure_ascii=False)

        # Zip the directory
        with zipfile.ZipFile(output_zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
            for root, _, files in os.walk(temp_dir):
                for file in files:
                    file_path = Path(root) / file
                    arcname = file_path.relative_to(temp_dir)
                    zipf.write(file_path, arcname)

    return output_zip_path


def upload_bundle_to_vps(
    zip_path: Path,
    remote_path: str,
    ssh_host: str,
    ssh_user: str = "root",
) -> bool:
    """
    Uploads the bundle zip file to the VPS using SCP.
    """
    zip_path = Path(zip_path)
    if not zip_path.exists():
        raise FileNotFoundError(f"Bundle file not found: {zip_path}")

    # Ensure remote directory exists on VPS beforehand
    # We run a quick ssh mkdir command
    remote_dir = str(Path(remote_path).parent)
    mkdir_cmd = [
        "ssh",
        "-o", "BatchMode=yes",
        "-o", "ConnectTimeout=15",
        f"{ssh_user}@{ssh_host}",
        f"mkdir -p {remote_dir}"
    ]
    mkdir_result = subprocess.run(mkdir_cmd, capture_output=True, text=True)
    if mkdir_result.returncode != 0:
        raise RuntimeError(
            f"SSH connection or remote mkdir failed (exit {mkdir_result.returncode}): "
            f"{mkdir_result.stderr.strip()}"
        )

    scp_cmd = [
        "scp",
        "-o", "BatchMode=yes",
        "-o", "ConnectTimeout=15",
        str(zip_path),
        f"{ssh_user}@{ssh_host}:{remote_path}"
    ]
    
    result = subprocess.run(scp_cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"SCP upload failed: {result.stderr}")
    
    return True
